<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RackProvisioner.Core\RackProvisioner.Core.csproj" />
    <ProjectReference Include="..\RackProvisioner.Data\RackProvisioner.Data.csproj" />
    <ProjectReference Include="..\RackProvisioner.Domain\RackProvisioner.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
