"""Canonical event names used between application modules."""
INVENTORY_SAVED = "inventory.saved"
INVENTORY_VERIFIED = "inventory.verified"
DISCOVERY_COMPLETED = "discovery.completed"
LLDP_COMPLETED = "lldp.completed"
SKU_REVISION_SAVED = "sku.revision.saved"
